Draft updated README with usage instructions
liveview-native/liveview-native-live-form pull request #8
Opened 2024-01-30 18:14 UTC by BrooklinJazz

README format based on https://github.com/liveview-native/liveview-native-swiftui-mapkit

2024-01-30 18:34 UTC, carson-katri requested changes

2024-01-30 18:34 UTC, carson-katri commented on README.md
> +`liveview-native-forms` is an add-on library for [LiveView Native SwiftUI](https://github.com/liveviewnative/liveview-client-swiftui). It adds support for conveniently working with control views grou
```suggestion
`liveview-native-live-form` is an add-on library for [LiveView Native SwiftUI](https://github.com/liveviewnative/liveview-client-swiftui). It adds support for conveniently working with control views grouped within a single form so you can use Phoenix [Form Bindings](https://hexdocs.pm/phoenix_live_view/form-bindings.html) within a LiveView Native application.
```

2024-01-30 18:34 UTC, carson-katri commented on README.md
> +//  KinoLiveView
Might be good to remove this header comment.

2024-01-30 18:34 UTC, carson-katri commented on README.md
> +      <TextField name="my-text" >Placeholder</TextField>
```suggestion
      <TextField name="my-text">Placeholder</TextField>
```

2024-02-05 18:01 UTC, BrooklinJazz commented
@carson-katri all feedback has been addressed.

2024-09-17 13:21 UTC, bcardarella commented
Closing in favor of using the newer syntax

2024-09-17 13:21 UTC, closed without merging